### ISSUE TITLE
Error in README.md example

### ISSUE THREAD

**Issue by ugnelis** [aleksas/phonology_engine#8]
In my opinion, in example of the Process section (https://github.com/aleksas/phonology_engine#process section) there is a mistake:

Syllables are wrongly found. Code should return not `'number_stressed_word': 'TRI0-SDE-ŠIMT',` but `'number_stressed_word': 'TRI0S-DE-ŠIMT'`.

Cheers!
Ugnius

**Comment by aleksas** [comment]
Will look into It.

**Comment by aleksas** [comment]
The answer from Liepa synthesizer author (in Lithuanian):

> Dvejetai skiemenų ribų masyve žymi skiemenų pabaigas, o pirmasis dvejetas - 
> pauzės prieš žodį pabaigą.
> Apie skiemenavimą galite pasiskaityti paskaitos konspekte:
> 
> https://klevas.mif.vu.lt/~pijus/CL/Skiemen.pdf
> 
> Lietuvių kalboje sudėtiniai žodžiai gali būti keliami arba remiantis skiemens struktūra, arba morfemomis.
> Sintezatorius sudurtinius žodžius skiemenuoja remiantis skiemens struktūra, tik
> priešdėliai atskiriami pagal morfemų ribą. 

Closing the issue

**Comment by ugnelis** [comment]
Nesigilinau į tekste esantį algoritmą, bet "trisdešimt" turi dvi šaknis, tai yra "tris" ir "dešimt".

**Comment by aleksas** [comment]
Skiemenavimas paimtas is sintezatoriaus, jis, panasu, skiriasi nuo mokyklinio. Jis matyt nelabai pades Lt gramatikos namu darbus spresti, bet gal pravers kuriant geresni sintezatoriu. Alternative yra sito skiemenavimo ismetimas.
